#!/usr/bin/env python3
"""
axFounder Telegram Bot
A complete task-based earning bot with admin controls,
FSM flows, SQLite database, referral system, and bilingual support.
"""

import asyncio
import logging
import os
import random
import sqlite3
from datetime import datetime, timedelta
from io import BytesIO

import openpyxl
from aiogram import Bot, Dispatcher, F, Router
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode
from aiogram.filters import Command, CommandStart
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.types import (
    BufferedInputFile,
    CallbackQuery,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    KeyboardButton,
    Message,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
)

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
BOT_TOKEN = os.environ.get("BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")
MAIN_ADMIN = 8907284640  # Hardcoded main admin ID
_second_admin_raw = os.environ.get("ADMIN_ID", "").strip()
SECOND_ADMIN_ID = int(_second_admin_raw) if _second_admin_raw.isdigit() else 0  # From Railway env var

TASK_PRICE = 0.0450
MIN_WITHDRAW = 0.20
REFERRAL_COMMISSION = 0.10  # 10%
DEFAULT_PASSWORD = "axFacebook@18"
DB_PATH = "tasks.db"
XLSX_PATH = "data/approved_submissions.xlsx"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def is_admin(user_id: int) -> bool:
    """Check if a user is an admin."""
    return user_id in (MAIN_ADMIN, SECOND_ADMIN_ID)


# ──────────────────────────────────────────
# TRANSLATIONS
# ──────────────────────────────────────────
TRANSLATIONS = {
    "en": {
        "welcome": (
            "👋 <b>Welcome to axFounder!</b>\n\n"
            "💼 Complete simple tasks.\n"
            "💰 Earn money.\n"
            "🚀 Withdraw anytime after reaching the minimum balance.\n\n"
            "Choose an option below."
        ),
        "balance_title": "💰 <b>Your Balance</b>\n\n${balance:.4f}",
        "tasks_menu": "📋 <b>Choose a task:</b>",
        "task_fb_btn": "Facebook Cookies (No Mail) - $0.0450",
        "cancel_btn": "Cancel ❌",
        "balance_btn": "💸 Balance",
        "tasks_btn": "📋 Tasks",
        "workinfo_btn": "👤 Work Info",
        "withdraw_btn": "📥 Withdraw",
        "language_btn": "🌍 Language",
        "referrals_btn": "👥 My Referrals",
        "start_btn": "▶️ Start",
        "send_uid_btn": "#️⃣ Send UID",
        "registered_btn": "Account Registered ✅",
        "fb_task_info": (
            "⏳ <b>Review Time</b>\n64 Minutes\n\n"
            "📋 <b>Task</b>\n🌟 Create Facebook Account\n\n"
            "📄 <b>Description</b>\n\n"
            "🔐 <b>REQUIRED</b>\n\n"
            "You <b>MUST</b> use the information generated by this bot.\n\n"
            "Using your own account information will cause automatic rejection.\n\n"
            "Follow all instructions carefully.\n\n"
            "⏳ <b>Estimated Review:</b> 64 Minutes"
        ),
        "generated_info": (
            "✅ <b>Your Account Details</b>\n\n"
            "👤 <b>First Name:</b> {first}\n"
            "👤 <b>Last Name:</b> {last}\n"
            "🔑 <b>Password:</b> <code>{password}</code>\n\n"
            "⚠️ Use ONLY this information to create your Facebook account."
        ),
        "ask_uid": "📥 <b>Send your Facebook UID</b>",
        "ask_cookies": "🍪 <b>Send your Facebook Cookies</b>",
        "submission_saved": (
            "✅ <b>Submission saved!</b>\n\n"
            "⏳ Status: <b>Pending</b>\n"
            "Your balance will be updated after admin approval."
        ),
        "already_pending": "⚠️ You already have a pending submission. Please wait for it to be reviewed.",
        "work_info": (
            "📊 <b>Work Information</b>\n\n"
            "📤 Submitted: <b>{submitted}</b>\n"
            "✅ Approved: <b>{approved}</b>\n"
            "❌ Rejected: <b>{rejected}</b>\n"
            "⏳ Pending: <b>{pending}</b>"
        ),
        "withdraw_menu": "📥 <b>Choose withdrawal method:</b>",
        "usdt_btn": "USDT (BEP20)",
        "ask_wallet": "💳 <b>Send your BEP20 wallet address:</b>",
        "ask_amount": (
            "💵 <b>Enter withdrawal amount:</b>\n\n"
            "Minimum: <b>$0.20 USD</b>\n"
            "Your balance: <b>${balance:.4f}</b>"
        ),
        "withdraw_low": "❌ <b>Insufficient balance.</b>\n\nMinimum withdrawal is $0.20. Your balance: ${balance:.4f}",
        "withdraw_sent": "✅ <b>Withdrawal request submitted!</b>\n\nAdmin will process it shortly.",
        "invalid_amount": "❌ Invalid amount. Please enter a valid number.",
        "language_menu": "🌍 <b>Choose your language:</b>",
        "lang_saved": "✅ Language updated!",
        "referrals_info": (
            "👥 <b>My Referrals</b>\n\n"
            "👥 Total Referrals: <b>{total}</b>\n"
            "🆕 Joined Last 24h: <b>{last24}</b>\n"
            "💰 Earned Last 30 Days: <b>${earned30:.4f}</b>\n"
            "💵 Earned Last 24 Hours: <b>${earned24:.4f}</b>\n\n"
            "🔗 <b>Your Referral Link:</b>\n"
            "<code>https://t.me/{bot_username}?start={user_id}</code>"
        ),
        "home": "🏠 Returned to home.",
        "approved_notify": (
            "✅ <b>Your submission has been approved!</b>\n\n"
            "💰 <b>${amount:.4f}</b> has been added to your balance."
        ),
        "rejected_notify": "❌ <b>Your submission has been rejected.</b>\n\nPlease review the task requirements and try again.",
        "no_pending": "✅ No pending submissions to review.",
        "pass_updated": "✅ Password updated to: <code>{password}</code>",
        "pass_usage": "Usage: /pass <new_password>",
        "withdraw_notify": (
            "🔔 <b>New Withdrawal Request</b>\n\n"
            "👤 User: {name} (@{username})\n"
            "🆔 ID: {user_id}\n"
            "💳 Wallet: <code>{wallet}</code>\n"
            "💵 Amount: <b>${amount:.4f}</b>"
        ),
        "bangla_btn": "Bangla 🇧🇩",
        "english_btn": "English 🇺🇸",
    },
    "bn": {
        "welcome": (
            "👋 <b>axFounder-এ স্বাগতম!</b>\n\n"
            "💼 সহজ কাজ সম্পন্ন করুন।\n"
            "💰 অর্থ উপার্জন করুন।\n"
            "🚀 ন্যূনতম ব্যালেন্সে পৌঁছানোর পরে যেকোনো সময় উইথড্র করুন।\n\n"
            "নিচে একটি বিকল্প বেছে নিন।"
        ),
        "balance_title": "💰 <b>আপনার ব্যালেন্স</b>\n\n${balance:.4f}",
        "tasks_menu": "📋 <b>একটি কাজ বেছে নিন:</b>",
        "task_fb_btn": "Facebook Cookies (No Mail) - $0.0450",
        "cancel_btn": "বাতিল ❌",
        "balance_btn": "💸 ব্যালেন্স",
        "tasks_btn": "📋 কাজ",
        "workinfo_btn": "👤 কাজের তথ্য",
        "withdraw_btn": "📥 উইথড্র",
        "language_btn": "🌍 ভাষা",
        "referrals_btn": "👥 আমার রেফারেল",
        "start_btn": "▶️ শুরু করুন",
        "send_uid_btn": "#️⃣ UID পাঠান",
        "registered_btn": "অ্যাকাউন্ট নিবন্ধিত ✅",
        "fb_task_info": (
            "⏳ <b>রিভিউ সময়</b>\n৬৪ মিনিট\n\n"
            "📋 <b>কাজ</b>\n🌟 Facebook অ্যাকাউন্ট তৈরি করুন\n\n"
            "📄 <b>বিবরণ</b>\n\n"
            "🔐 <b>আবশ্যক</b>\n\n"
            "আপনাকে <b>অবশ্যই</b> এই বটের তৈরি তথ্য ব্যবহার করতে হবে।\n\n"
            "নিজের তথ্য ব্যবহার করলে স্বয়ংক্রিয়ভাবে প্রত্যাখ্যান হবে।\n\n"
            "সমস্ত নির্দেশাবলী সাবধানে অনুসরণ করুন।\n\n"
            "⏳ <b>আনুমানিক রিভিউ:</b> ৬৪ মিনিট"
        ),
        "generated_info": (
            "✅ <b>আপনার অ্যাকাউন্ট তথ্য</b>\n\n"
            "👤 <b>প্রথম নাম:</b> {first}\n"
            "👤 <b>শেষ নাম:</b> {last}\n"
            "🔑 <b>পাসওয়ার্ড:</b> <code>{password}</code>\n\n"
            "⚠️ Facebook অ্যাকাউন্ট তৈরিতে শুধুমাত্র এই তথ্য ব্যবহার করুন।"
        ),
        "ask_uid": "📥 <b>আপনার Facebook UID পাঠান</b>",
        "ask_cookies": "🍪 <b>আপনার Facebook Cookies পাঠান</b>",
        "submission_saved": (
            "✅ <b>জমা সংরক্ষিত হয়েছে!</b>\n\n"
            "⏳ স্ট্যাটাস: <b>পেন্ডিং</b>\n"
            "অ্যাডমিন অনুমোদনের পরে ব্যালেন্স আপডেট হবে।"
        ),
        "already_pending": "⚠️ আপনার একটি পেন্ডিং সাবমিশন আছে। রিভিউ না হওয়া পর্যন্ত অপেক্ষা করুন।",
        "work_info": (
            "📊 <b>কাজের তথ্য</b>\n\n"
            "📤 জমা দেওয়া: <b>{submitted}</b>\n"
            "✅ অনুমোদিত: <b>{approved}</b>\n"
            "❌ প্রত্যাখ্যাত: <b>{rejected}</b>\n"
            "⏳ পেন্ডিং: <b>{pending}</b>"
        ),
        "withdraw_menu": "📥 <b>উইথড্র পদ্ধতি বেছে নিন:</b>",
        "usdt_btn": "USDT (BEP20)",
        "ask_wallet": "💳 <b>আপনার BEP20 ওয়ালেট ঠিকানা পাঠান:</b>",
        "ask_amount": (
            "💵 <b>উইথড্র পরিমাণ লিখুন:</b>\n\n"
            "সর্বনিম্ন: <b>$0.20 USD</b>\n"
            "আপনার ব্যালেন্স: <b>${balance:.4f}</b>"
        ),
        "withdraw_low": "❌ <b>অপর্যাপ্ত ব্যালেন্স।</b>\n\nসর্বনিম্ন উইথড্র $0.20। আপনার ব্যালেন্স: ${balance:.4f}",
        "withdraw_sent": "✅ <b>উইথড্র অনুরোধ জমা দেওয়া হয়েছে!</b>\n\nঅ্যাডমিন শীঘ্রই প্রক্রিয়া করবেন।",
        "invalid_amount": "❌ অবৈধ পরিমাণ। একটি সঠিক সংখ্যা লিখুন।",
        "language_menu": "🌍 <b>আপনার ভাষা বেছে নিন:</b>",
        "lang_saved": "✅ ভাষা আপডেট হয়েছে!",
        "referrals_info": (
            "👥 <b>আমার রেফারেল</b>\n\n"
            "👥 মোট রেফারেল: <b>{total}</b>\n"
            "🆕 গত ২৪ ঘণ্টায় যোগদান: <b>{last24}</b>\n"
            "💰 গত ৩০ দিনে উপার্জন: <b>${earned30:.4f}</b>\n"
            "💵 গত ২৪ ঘণ্টায় উপার্জন: <b>${earned24:.4f}</b>\n\n"
            "🔗 <b>আপনার রেফারেল লিঙ্ক:</b>\n"
            "<code>https://t.me/{bot_username}?start={user_id}</code>"
        ),
        "home": "🏠 হোমে ফিরে এসেছেন।",
        "approved_notify": (
            "✅ <b>আপনার সাবমিশন অনুমোদিত হয়েছে!</b>\n\n"
            "💰 <b>${amount:.4f}</b> আপনার ব্যালেন্সে যোগ হয়েছে।"
        ),
        "rejected_notify": "❌ <b>আপনার সাবমিশন প্রত্যাখ্যাত হয়েছে।</b>\n\nটাস্কের নিয়মাবলী দেখুন এবং আবার চেষ্টা করুন।",
        "no_pending": "✅ রিভিউ করার মতো কোনো পেন্ডিং সাবমিশন নেই।",
        "pass_updated": "✅ পাসওয়ার্ড আপডেট হয়েছে: <code>{password}</code>",
        "pass_usage": "ব্যবহার: /pass <নতুন_পাসওয়ার্ড>",
        "withdraw_notify": (
            "🔔 <b>নতুন উইথড্র অনুরোধ</b>\n\n"
            "👤 ব্যবহারকারী: {name} (@{username})\n"
            "🆔 ID: {user_id}\n"
            "💳 ওয়ালেট: <code>{wallet}</code>\n"
            "💵 পরিমাণ: <b>${amount:.4f}</b>"
        ),
        "bangla_btn": "বাংলা 🇧🇩",
        "english_btn": "ইংরেজি 🇺🇸",
    },
}


def t(user_id: int, key: str, **kwargs) -> str:
    """
    Translate a key for a given user.
    Falls back to English if the key is missing in the user's language.
    """
    lang = get_user_lang(user_id)
    text = TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(
        key, TRANSLATIONS["en"].get(key, key)
    )
    if kwargs:
        try:
            return text.format(**kwargs)
        except KeyError:
            return text
    return text


# ─────────────────────────────────────────────
# DATABASE SETUP
# ─────────────────────────────────────────────
def get_db() -> sqlite3.Connection:
    """Return a SQLite connection with row_factory for dict-like access."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    """Initialize all database tables."""
    conn = get_db()
    c = conn.cursor()

    # Users table
    c.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id          INTEGER PRIMARY KEY,
            username    TEXT,
            full_name   TEXT,
            balance     REAL DEFAULT 0.0,
            language    TEXT DEFAULT 'en',
            referred_by INTEGER,
            joined_at   TEXT DEFAULT (datetime('now'))
        )
    """)

    # Submissions table
    c.execute("""
        CREATE TABLE IF NOT EXISTS submissions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id         INTEGER,
            username        TEXT,
            uid             TEXT,
            cookies         TEXT,
            gen_first_name  TEXT,
            gen_last_name   TEXT,
            gen_password    TEXT,
            status          TEXT DEFAULT 'pending',
            submitted_at    TEXT DEFAULT (datetime('now')),
            reviewed_at     TEXT
        )
    """)

    # Withdrawals table
    c.execute("""
        CREATE TABLE IF NOT EXISTS withdrawals (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id     INTEGER,
            wallet      TEXT,
            amount      REAL,
            status      TEXT DEFAULT 'pending',
            requested_at TEXT DEFAULT (datetime('now'))
        )
    """)

    # Settings table (bot-wide config like current password)
    c.execute("""
        CREATE TABLE IF NOT EXISTS settings (
            key   TEXT PRIMARY KEY,
            value TEXT
        )
    """)
    # Insert default password if not present
    c.execute(
        "INSERT OR IGNORE INTO settings (key, value) VALUES ('task_password', ?)",
        (DEFAULT_PASSWORD,),
    )

    # Referral earnings log
    c.execute("""
        CREATE TABLE IF NOT EXISTS referrals (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            referrer_id INTEGER,
            referred_id INTEGER,
            amount      REAL,
            earned_at   TEXT DEFAULT (datetime('now'))
        )
    """)

    conn.commit()
    conn.close()


# ─────────────────────────────────────────────
# XLSX HELPER FUNCTIONS
# ─────────────────────────────────────────────
def ensure_xlsx():
    """Create the xlsx file with headers if it doesn't exist."""
    os.makedirs(os.path.dirname(XLSX_PATH), exist_ok=True)
    if not os.path.exists(XLSX_PATH):
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Approved Submissions"
        ws["A1"] = "UID"
        ws["B1"] = "Cookies"
        wb.save(XLSX_PATH)


def append_to_xlsx(uid: str, cookies: str):
    """Append a new approved submission row to the persistent xlsx file."""
    ensure_xlsx()
    wb = openpyxl.load_workbook(XLSX_PATH)
    ws = wb.active
    ws.append([uid, cookies])
    wb.save(XLSX_PATH)


def reset_xlsx():
    """Clear all data rows from xlsx, keeping only the header."""
    os.makedirs(os.path.dirname(XLSX_PATH), exist_ok=True)
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Approved Submissions"
    ws["A1"] = "UID"
    ws["B1"] = "Cookies"
    wb.save(XLSX_PATH)


def get_xlsx_bytes() -> bytes:
    """Read the current xlsx file and return as bytes."""
    ensure_xlsx()
    with open(XLSX_PATH, "rb") as f:
        return f.read()


def get_xlsx_row_count() -> int:
    """Return number of data rows (excluding header) in xlsx."""
    ensure_xlsx()
    wb = openpyxl.load_workbook(XLSX_PATH, read_only=True)
    ws = wb.active
    count = ws.max_row - 1 if ws.max_row and ws.max_row > 1 else 0
    wb.close()
    return count


# ─────────────────────────────────────────────
# DATABASE HELPER FUNCTIONS
# ─────────────────────────────────────────────
def ensure_user(user_id: int, username: str, full_name: str, referred_by: int = None):
    """Insert user if not exists. Handles referral linking."""
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT id FROM users WHERE id = ?", (user_id,))
    row = c.fetchone()
    if not row:
        c.execute(
            "INSERT INTO users (id, username, full_name, referred_by) VALUES (?, ?, ?, ?)",
            (user_id, username, full_name, referred_by),
        )
        conn.commit()
    else:
        # Update username/name in case they changed
        c.execute(
            "UPDATE users SET username = ?, full_name = ? WHERE id = ?",
            (username, full_name, user_id),
        )
        conn.commit()
    conn.close()


def get_user(user_id: int) -> dict | None:
    """Fetch a user row as a dict."""
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT * FROM users WHERE id = ?", (user_id,))
    row = c.fetchone()
    conn.close()
    return dict(row) if row else None


def get_user_lang(user_id: int) -> str:
    """Return the user's preferred language code."""
    user = get_user(user_id)
    if user:
        return user.get("language", "en")
    return "en"


def set_user_lang(user_id: int, lang: str):
    """Update user language preference."""
    conn = get_db()
    conn.execute("UPDATE users SET language = ? WHERE id = ?", (lang, user_id))
    conn.commit()
    conn.close()


def get_balance(user_id: int) -> float:
    """Return the user's current balance."""
    user = get_user(user_id)
    return user["balance"] if user else 0.0


def add_balance(user_id: int, amount: float):
    """Add an amount to a user's balance."""
    conn = get_db()
    conn.execute(
        "UPDATE users SET balance = balance + ? WHERE id = ?", (amount, user_id)
    )
    conn.commit()
    conn.close()


def deduct_balance(user_id: int, amount: float):
    """Deduct an amount from a user's balance."""
    conn = get_db()
    conn.execute(
        "UPDATE users SET balance = balance - ? WHERE id = ?", (amount, user_id)
    )
    conn.commit()
    conn.close()


def get_task_password() -> str:
    """Retrieve current task password from settings."""
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT value FROM settings WHERE key = 'task_password'")
    row = c.fetchone()
    conn.close()
    return row["value"] if row else DEFAULT_PASSWORD


def set_task_password(new_password: str):
    """Update the task password in settings."""
    conn = get_db()
    conn.execute(
        "UPDATE settings SET value = ? WHERE key = 'task_password'", (new_password,)
    )
    conn.commit()
    conn.close()


def has_pending_submission(user_id: int) -> bool:
    """Check if the user already has a pending submission."""
    conn = get_db()
    c = conn.cursor()
    c.execute(
        "SELECT id FROM submissions WHERE user_id = ? AND status = 'pending'",
        (user_id,),
    )
    row = c.fetchone()
    conn.close()
    return row is not None


def save_submission(
    user_id: int,
    username: str,
    uid: str,
    cookies: str,
    first: str,
    last: str,
    password: str,
):
    """Save a new task submission with pending status."""
    conn = get_db()
    conn.execute(
        """INSERT INTO submissions
           (user_id, username, uid, cookies, gen_first_name, gen_last_name, gen_password)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        (user_id, username, uid, cookies, first, last, password),
    )
    conn.commit()
    conn.close()


def get_pending_submissions() -> list:
    """Return all pending submissions ordered by time."""
    conn = get_db()
    c = conn.cursor()
    c.execute(
        "SELECT * FROM submissions WHERE status = 'pending' ORDER BY submitted_at ASC"
    )
    rows = [dict(r) for r in c.fetchall()]
    conn.close()
    return rows


def get_submission_by_id(sub_id: int) -> dict | None:
    """Fetch a single submission by ID."""
    conn = get_db()
    c = conn.cursor()
    c.execute("SELECT * FROM submissions WHERE id = ?", (sub_id,))
    row = c.fetchone()
    conn.close()
    return dict(row) if row else None


def update_submission_status(sub_id: int, status: str):
    """Update submission status and set reviewed_at timestamp."""
    conn = get_db()
    conn.execute(
        "UPDATE submissions SET status = ?, reviewed_at = datetime('now') WHERE id = ?",
        (status, sub_id),
    )
    conn.commit()
    conn.close()


def get_user_submission_stats(user_id: int) -> dict:
    """Return submission counts grouped by status for a user."""
    conn = get_db()
    c = conn.cursor()
    stats = {"submitted": 0, "approved": 0, "rejected": 0, "pending": 0}
    c.execute(
        "SELECT status, COUNT(*) as cnt FROM submissions WHERE user_id = ? GROUP BY status",
        (user_id,),
    )
    for row in c.fetchall():
        s = row["status"]
        if s in stats:
            stats[s] = row["cnt"]
    # Total submitted = sum of all statuses
    stats["submitted"] = stats["approved"] + stats["rejected"] + stats["pending"]
    conn.close()
    return stats


def save_withdrawal(user_id: int, wallet: str, amount: float):
    """Record a withdrawal request."""
    conn = get_db()
    conn.execute(
        "INSERT INTO withdrawals (user_id, wallet, amount) VALUES (?, ?, ?)",
        (user_id, wallet, amount),
    )
    conn.commit()
    conn.close()


def get_global_stats() -> dict:
    """Return bot-wide statistics for the admin /stats command."""
    conn = get_db()
    c = conn.cursor()

    c.execute("SELECT COUNT(*) as cnt FROM users")
    total_users = c.fetchone()["cnt"]

    c.execute("SELECT COUNT(*) as cnt FROM submissions")
    total_submitted = c.fetchone()["cnt"]

    c.execute("SELECT COUNT(*) as cnt FROM submissions WHERE status = 'approved'")
    total_approved = c.fetchone()["cnt"]

    c.execute("SELECT COUNT(*) as cnt FROM submissions WHERE status = 'rejected'")
    total_rejected = c.fetchone()["cnt"]

    c.execute("SELECT COUNT(*) as cnt FROM submissions WHERE status = 'pending'")
    total_pending = c.fetchone()["cnt"]

    c.execute(
        "SELECT COALESCE(SUM(amount), 0) as total FROM withdrawals WHERE status = 'paid'"
    )
    total_paid = c.fetchone()["total"]

    c.execute("SELECT COALESCE(SUM(amount), 0) as total FROM withdrawals")
    total_withdrawals = c.fetchone()["total"]

    conn.close()
    return {
        "total_users": total_users,
        "submitted": total_submitted,
        "approved": total_approved,
        "rejected": total_rejected,
        "pending": total_pending,
        "total_paid": total_paid,
        "total_withdrawals": total_withdrawals,
    }


def get_referral_stats(user_id: int, bot_username: str) -> dict:
    """Return referral stats for a user."""
    conn = get_db()
    c = conn.cursor()
    now = datetime.utcnow()

    # Total referrals
    c.execute(
        "SELECT COUNT(*) as cnt FROM users WHERE referred_by = ?", (user_id,)
    )
    total = c.fetchone()["cnt"]

    # Joined last 24h
    since_24h = (now - timedelta(hours=24)).strftime("%Y-%m-%d %H:%M:%S")
    c.execute(
        "SELECT COUNT(*) as cnt FROM users WHERE referred_by = ? AND joined_at >= ?",
        (user_id, since_24h),
    )
    last24 = c.fetchone()["cnt"]

    # Earned last 30 days
    since_30d = (now - timedelta(days=30)).strftime("%Y-%m-%d %H:%M:%S")
    c.execute(
        "SELECT COALESCE(SUM(amount), 0) as total FROM referrals WHERE referrer_id = ? AND earned_at >= ?",
        (user_id, since_30d),
    )
    earned30 = c.fetchone()["total"]

    # Earned last 24h
    c.execute(
        "SELECT COALESCE(SUM(amount), 0) as total FROM referrals WHERE referrer_id = ? AND earned_at >= ?",
        (user_id, since_24h),
    )
    earned24 = c.fetchone()["total"]

    conn.close()
    return {
        "total": total,
        "last24": last24,
        "earned30": earned30,
        "earned24": earned24,
        "bot_username": bot_username,
        "user_id": user_id,
    }


def log_referral_earning(referrer_id: int, referred_id: int, amount: float):
    """Record a referral commission earned."""
    conn = get_db()
    conn.execute(
        "INSERT INTO referrals (referrer_id, referred_id, amount) VALUES (?, ?, ?)",
        (referrer_id, referred_id, amount),
    )
    conn.commit()
    conn.close()


# ─────────────────────────────────────────────
# NAME GENERATION
# ─────────────────────────────────────────────
FIRST_NAMES = [
    "James", "John", "Robert", "Michael", "William", "David", "Richard",
    "Joseph", "Thomas", "Charles", "Christopher", "Daniel", "Matthew",
    "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua",
    "Emma", "Olivia", "Ava", "Isabella", "Sophia", "Mia", "Charlotte",
    "Amelia", "Harper", "Evelyn", "Emily", "Elizabeth", "Sofia", "Grace",
    "Chloe", "Victoria", "Madison", "Eleanor", "Lily", "Hannah",
]

LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
    "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark",
    "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King",
    "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
]


def generate_name() -> tuple[str, str]:
    """Generate a random realistic English first and last name."""
    return random.choice(FIRST_NAMES), random.choice(LAST_NAMES)


# ─────────────────────────────────────────────
# KEYBOARDS
# ─────────────────────────────────────────────
def home_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Build the main home reply keyboard based on user language."""
    return ReplyKeyboardMarkup(
        keyboard=[
            [
                KeyboardButton(text=t(user_id, "balance_btn")),
                KeyboardButton(text=t(user_id, "tasks_btn")),
            ],
            [KeyboardButton(text=t(user_id, "workinfo_btn"))],
            [
                KeyboardButton(text=t(user_id, "withdraw_btn")),
                KeyboardButton(text=t(user_id, "language_btn")),
            ],
            [KeyboardButton(text=t(user_id, "referrals_btn"))],
        ],
        resize_keyboard=True,
    )


def cancel_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Single-row cancel keyboard."""
    return ReplyKeyboardMarkup(
        keyboard=[[KeyboardButton(text=t(user_id, "cancel_btn"))]],
        resize_keyboard=True,
    )


def task_list_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Tasks menu keyboard."""
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=t(user_id, "task_fb_btn"))],
            [KeyboardButton(text=t(user_id, "cancel_btn"))],
        ],
        resize_keyboard=True,
    )


def fb_task_start_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Start / Cancel keyboard for FB task description."""
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=t(user_id, "start_btn"))],
            [KeyboardButton(text=t(user_id, "cancel_btn"))],
        ],
        resize_keyboard=True,
    )


def uid_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Send UID / Cancel keyboard."""
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=t(user_id, "send_uid_btn"))],
            [KeyboardButton(text=t(user_id, "cancel_btn"))],
        ],
        resize_keyboard=True,
    )


def registered_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Account Registered / Cancel keyboard."""
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=t(user_id, "registered_btn"))],
            [KeyboardButton(text=t(user_id, "cancel_btn"))],
        ],
        resize_keyboard=True,
    )


def withdraw_method_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Withdrawal method keyboard."""
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=t(user_id, "usdt_btn"))],
            [KeyboardButton(text=t(user_id, "cancel_btn"))],
        ],
        resize_keyboard=True,
    )


def language_keyboard(user_id: int) -> ReplyKeyboardMarkup:
    """Language selection keyboard."""
    return ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton(text=t(user_id, "bangla_btn"))],
            [KeyboardButton(text=t(user_id, "english_btn"))],
            [KeyboardButton(text=t(user_id, "cancel_btn"))],
        ],
        resize_keyboard=True,
    )


def review_inline_keyboard(sub_id: int, index: int, total: int) -> InlineKeyboardMarkup:
    """Inline keyboard for admin submission review."""
    buttons = []
    nav_row = []
    if index > 0:
        nav_row.append(
            InlineKeyboardButton(text="⏮ Previous", callback_data=f"rev_prev_{index}")
        )
    if index < total - 1:
        nav_row.append(
            InlineKeyboardButton(text="Next ⏭", callback_data=f"rev_next_{index}")
        )
    if nav_row:
        buttons.append(nav_row)
    buttons.append([
        InlineKeyboardButton(text="Rejected ❌", callback_data=f"rev_reject_{sub_id}"),
        InlineKeyboardButton(text="Approved ✅", callback_data=f"rev_approve_{sub_id}"),
    ])
    return InlineKeyboardMarkup(inline_keyboard=buttons)


# ─────────────────────────────────────────────
# FSM STATES
# ─────────────────────────────────────────────
class TaskFSM(StatesGroup):
    """States for the Facebook task flow."""
    viewing_task = State()
    task_started = State()       # Shown generated info, waiting for "Send UID"
    waiting_uid = State()        # Waiting for UID text input
    waiting_cookies = State()    # Waiting for cookies text input
    confirming = State()         # Waiting for "Account Registered" confirmation


class WithdrawFSM(StatesGroup):
    """States for the withdrawal flow."""
    choosing_method = State()
    waiting_wallet = State()
    waiting_amount = State()


class LanguageFSM(StatesGroup):
    """States for language selection."""
    choosing = State()


# ─────────────────────────────────────────────
# ROUTER & BOT SETUP
# ─────────────────────────────────────────────
router = Router()
bot: Bot = None  # Initialized in main()


# ─────────────────────────────────────────────
# /start HANDLER
# ─────────────────────────────────────────────
@router.message(CommandStart())
async def cmd_start(message: Message, state: FSMContext):
    """Handle /start command and optional referral parameter."""
    await state.clear()
    user = message.from_user
    args = message.text.split(maxsplit=1)

    referred_by = None
    if len(args) > 1:
        try:
            ref_id = int(args[1])
            # Don't allow self-referral
            if ref_id != user.id:
                referred_by = ref_id
        except ValueError:
            pass

    ensure_user(
        user.id,
        user.username or "",
        user.full_name or "",
        referred_by=referred_by,
    )

    await message.answer(
        t(user.id, "welcome"),
        reply_markup=home_keyboard(user.id),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# BALANCE HANDLER
# ─────────────────────────────────────────────
@router.message(F.text.in_({"💸 Balance", "💸 ব্যালেন্স"}))
async def handle_balance(message: Message, state: FSMContext):
    """Show realtime balance."""
    await state.clear()
    uid = message.from_user.id
    balance = get_balance(uid)
    await message.answer(
        t(uid, "balance_title", balance=balance),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# TASKS MENU HANDLER
# ─────────────────────────────────────────────
@router.message(F.text.in_({"📋 Tasks", "📋 কাজ"}))
async def handle_tasks(message: Message, state: FSMContext):
    """Show the tasks menu."""
    await state.clear()
    uid = message.from_user.id
    await message.answer(
        t(uid, "tasks_menu"),
        reply_markup=task_list_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# FACEBOOK TASK — DESCRIPTION
# ─────────────────────────────────────────────
@router.message(F.text == "Facebook Cookies (No Mail) - $0.0450")
async def handle_fb_task(message: Message, state: FSMContext):
    """Show Facebook task description and set state."""
    uid = message.from_user.id

    # Block if user already has a pending submission
    if has_pending_submission(uid):
        await message.answer(
            t(uid, "already_pending"),
            parse_mode=ParseMode.HTML,
        )
        return

    await state.set_state(TaskFSM.viewing_task)
    await message.answer(
        t(uid, "fb_task_info"),
        reply_markup=fb_task_start_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# FACEBOOK TASK — START (generates info)
# ─────────────────────────────────────────────
@router.message(TaskFSM.viewing_task, F.text.in_({"▶️ Start", "▶️ শুরু করুন"}))
async def handle_task_start(message: Message, state: FSMContext):
    """Generate account info and show to user."""
    uid = message.from_user.id
    first, last = generate_name()
    password = get_task_password()

    # Store generated data in FSM context
    await state.update_data(
        gen_first=first, gen_last=last, gen_password=password
    )
    await state.set_state(TaskFSM.task_started)

    await message.answer(
        t(uid, "generated_info", first=first, last=last, password=password),
        reply_markup=uid_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# FACEBOOK TASK — REQUEST UID
# ─────────────────────────────────────────────
@router.message(TaskFSM.task_started, F.text.in_({"#️⃣ Send UID", "#️⃣ UID পাঠান"}))
async def handle_ask_uid(message: Message, state: FSMContext):
    """Ask for the Facebook UID."""
    uid = message.from_user.id
    await state.set_state(TaskFSM.waiting_uid)
    await message.answer(
        t(uid, "ask_uid"),
        reply_markup=cancel_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# FACEBOOK TASK — RECEIVE UID
# ─────────────────────────────────────────────
@router.message(TaskFSM.waiting_uid)
async def handle_receive_uid(message: Message, state: FSMContext):
    """Save UID and ask for cookies."""
    uid = message.from_user.id
    # Ignore cancel text — handled by global cancel handler
    await state.update_data(fb_uid=message.text.strip())
    await state.set_state(TaskFSM.waiting_cookies)
    await message.answer(
        t(uid, "ask_cookies"),
        reply_markup=cancel_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# FACEBOOK TASK — RECEIVE COOKIES
# ─────────────────────────────────────────────
@router.message(TaskFSM.waiting_cookies)
async def handle_receive_cookies(message: Message, state: FSMContext):
    """Save cookies and show confirmation keyboard."""
    uid = message.from_user.id
    await state.update_data(fb_cookies=message.text.strip())
    await state.set_state(TaskFSM.confirming)
    await message.answer(
        "✅ <b>Cookies received!</b>\n\nPress <b>Account Registered ✅</b> to submit.",
        reply_markup=registered_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# FACEBOOK TASK — FINAL SUBMISSION
# ─────────────────────────────────────────────
@router.message(TaskFSM.confirming, F.text.in_({"Account Registered ✅", "অ্যাকাউন্ট নিবন্ধিত ✅"}))
async def handle_submission(message: Message, state: FSMContext):
    """Finalize and save the task submission."""
    uid = message.from_user.id
    data = await state.get_data()

    save_submission(
        user_id=uid,
        username=message.from_user.username or "",
        uid=data.get("fb_uid", ""),
        cookies=data.get("fb_cookies", ""),
        first=data.get("gen_first", ""),
        last=data.get("gen_last", ""),
        password=data.get("gen_password", ""),
    )

    await state.clear()
    await message.answer(
        t(uid, "submission_saved"),
        reply_markup=home_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# WORK INFO HANDLER
# ─────────────────────────────────────────────
@router.message(F.text.in_({"👤 Work Info", "👤 কাজের তথ্য"}))
async def handle_work_info(message: Message, state: FSMContext):
    """Show user's submission statistics."""
    await state.clear()
    uid = message.from_user.id
    stats = get_user_submission_stats(uid)
    await message.answer(
        t(uid, "work_info", **stats),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# WITHDRAW FLOW
# ─────────────────────────────────────────────
@router.message(F.text.in_({"📥 Withdraw", "📥 উইথড্র"}))
async def handle_withdraw_menu(message: Message, state: FSMContext):
    """Show withdrawal method selection."""
    await state.clear()
    uid = message.from_user.id
    await state.set_state(WithdrawFSM.choosing_method)
    await message.answer(
        t(uid, "withdraw_menu"),
        reply_markup=withdraw_method_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


@router.message(WithdrawFSM.choosing_method, F.text == "USDT (BEP20)")
async def handle_usdt_selected(message: Message, state: FSMContext):
    """Ask for BEP20 wallet address."""
    uid = message.from_user.id
    await state.set_state(WithdrawFSM.waiting_wallet)
    await message.answer(
        t(uid, "ask_wallet"),
        reply_markup=cancel_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


@router.message(WithdrawFSM.waiting_wallet)
async def handle_wallet_received(message: Message, state: FSMContext):
    """Save wallet and ask for amount."""
    uid = message.from_user.id
    await state.update_data(wallet=message.text.strip())
    await state.set_state(WithdrawFSM.waiting_amount)
    balance = get_balance(uid)
    await message.answer(
        t(uid, "ask_amount", balance=balance),
        reply_markup=cancel_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


@router.message(WithdrawFSM.waiting_amount)
async def handle_amount_received(message: Message, state: FSMContext):
    """Validate amount and submit withdrawal request."""
    uid = message.from_user.id
    text = message.text.strip()

    try:
        amount = float(text)
    except ValueError:
        await message.answer(t(uid, "invalid_amount"), parse_mode=ParseMode.HTML)
        return

    balance = get_balance(uid)

    if amount < MIN_WITHDRAW or amount > balance:
        await message.answer(
            t(uid, "withdraw_low", balance=balance),
            parse_mode=ParseMode.HTML,
        )
        return

    data = await state.get_data()
    wallet = data.get("wallet", "")

    # Save withdrawal and deduct balance
    save_withdrawal(uid, wallet, amount)
    deduct_balance(uid, amount)

    user = message.from_user
    notify_text = t(
        MAIN_ADMIN,
        "withdraw_notify",
        name=user.full_name or "N/A",
        username=user.username or "N/A",
        user_id=uid,
        wallet=wallet,
        amount=amount,
    )

    # Notify both admins
    for admin_id in {MAIN_ADMIN, SECOND_ADMIN_ID}:
        if admin_id:
            try:
                await bot.send_message(admin_id, notify_text, parse_mode=ParseMode.HTML)
            except Exception:
                pass

    await state.clear()
    await message.answer(
        t(uid, "withdraw_sent"),
        reply_markup=home_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# LANGUAGE FLOW
# ─────────────────────────────────────────────
@router.message(F.text.in_({"🌍 Language", "🌍 ভাষা"}))
async def handle_language_menu(message: Message, state: FSMContext):
    """Show language selection keyboard."""
    await state.clear()
    uid = message.from_user.id
    await state.set_state(LanguageFSM.choosing)
    await message.answer(
        t(uid, "language_menu"),
        reply_markup=language_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


@router.message(
    LanguageFSM.choosing,
    F.text.in_({"Bangla 🇧🇩", "বাংলা 🇧🇩", "বাংলা", "Bangla"}),
)
async def handle_lang_bangla(message: Message, state: FSMContext):
    """Set language to Bangla."""
    uid = message.from_user.id
    set_user_lang(uid, "bn")
    await state.clear()
    await message.answer(
        t(uid, "lang_saved"),
        reply_markup=home_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


@router.message(
    LanguageFSM.choosing,
    F.text.in_({"English 🇺🇸", "ইংরেজি 🇺🇸", "English"}),
)
async def handle_lang_english(message: Message, state: FSMContext):
    """Set language to English."""
    uid = message.from_user.id
    set_user_lang(uid, "en")
    await state.clear()
    await message.answer(
        t(uid, "lang_saved"),
        reply_markup=home_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# REFERRALS HANDLER
# ─────────────────────────────────────────────
@router.message(F.text.in_({"👥 My Referrals", "👥 আমার রেফারেল"}))
async def handle_referrals(message: Message, state: FSMContext):
    """Show referral statistics and link."""
    await state.clear()
    uid = message.from_user.id
    me = await bot.get_me()
    stats = get_referral_stats(uid, me.username)
    await message.answer(
        t(uid, "referrals_info", **stats),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# UNIVERSAL CANCEL HANDLER
# ─────────────────────────────────────────────
@router.message(F.text.in_({"Cancel ❌", "বাতিল ❌"}))
async def handle_cancel(message: Message, state: FSMContext):
    """Cancel any active flow and return to home."""
    await state.clear()
    uid = message.from_user.id
    await message.answer(
        t(uid, "home"),
        reply_markup=home_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# ADMIN: /pass — Change task password
# ─────────────────────────────────────────────
@router.message(Command("pass"))
async def cmd_pass(message: Message):
    """Admin command to change the task-generated password."""
    uid = message.from_user.id
    if not is_admin(uid):
        return

    parts = message.text.split(maxsplit=1)
    if len(parts) < 2 or not parts[1].strip():
        await message.answer(t(uid, "pass_usage"), parse_mode=ParseMode.HTML)
        return

    new_pass = parts[1].strip()
    set_task_password(new_pass)
    await message.answer(
        t(uid, "pass_updated", password=new_pass), parse_mode=ParseMode.HTML
    )


# ─────────────────────────────────────────────
# ADMIN: /review — Browse & action pending submissions
# ─────────────────────────────────────────────
@router.message(Command("review"))
async def cmd_review(message: Message, state: FSMContext):
    """Start the admin review flow at index 0."""
    if not is_admin(message.from_user.id):
        return
    await send_review_card(message.chat.id, 0)


async def send_review_card(chat_id: int, index: int, edit_message_id: int = None):
    """
    Send or edit a review card for the pending submission at `index`.
    edit_message_id: if provided, edit that message instead of sending a new one.
    """
    subs = get_pending_submissions()
    if not subs:
        await bot.send_message(
            chat_id, "✅ No pending submissions to review.", parse_mode=ParseMode.HTML
        )
        return

    # Clamp index
    index = max(0, min(index, len(subs) - 1))
    sub = subs[index]

    text = (
        f"📋 <b>Submission #{sub['id']}</b>  [{index + 1}/{len(subs)}]\n\n"
        f"👤 <b>User ID:</b> {sub['user_id']}\n"
        f"🔗 <b>Username:</b> @{sub['username'] or 'N/A'}\n"
        f"🆔 <b>Facebook UID:</b> <code>{sub['uid']}</code>\n"
        f"🍪 <b>Cookies:</b>\n<code>{sub['cookies'][:300]}{'...' if len(sub['cookies']) > 300 else ''}</code>\n\n"
        f"👤 <b>Generated Name:</b> {sub['gen_first_name']} {sub['gen_last_name']}\n"
        f"🔑 <b>Password:</b> <code>{sub['gen_password']}</code>\n"
        f"🕐 <b>Submitted:</b> {sub['submitted_at']}\n"
        f"📊 <b>Status:</b> {sub['status'].upper()}"
    )
    keyboard = review_inline_keyboard(sub["id"], index, len(subs))

    if edit_message_id:
        try:
            await bot.edit_message_text(
                text,
                chat_id=chat_id,
                message_id=edit_message_id,
                reply_markup=keyboard,
                parse_mode=ParseMode.HTML,
            )
        except Exception:
            await bot.send_message(
                chat_id, text, reply_markup=keyboard, parse_mode=ParseMode.HTML
            )
    else:
        await bot.send_message(
            chat_id, text, reply_markup=keyboard, parse_mode=ParseMode.HTML
        )


@router.callback_query(F.data.startswith("rev_"))
async def handle_review_callback(call: CallbackQuery):
    """Handle Previous, Next, Approve, Reject inline buttons in review."""
    if not is_admin(call.from_user.id):
        await call.answer("Unauthorized.", show_alert=True)
        return

    data = call.data  # e.g. "rev_next_2", "rev_approve_5"
    parts = data.split("_")
    action = parts[1]  # prev | next | approve | reject

    if action == "next":
        current_index = int(parts[2])
        await call.answer()
        await send_review_card(
            call.message.chat.id, current_index + 1, call.message.message_id
        )

    elif action == "prev":
        current_index = int(parts[2])
        await call.answer()
        await send_review_card(
            call.message.chat.id, current_index - 1, call.message.message_id
        )

    elif action == "approve":
        sub_id = int(parts[2])
        sub = get_submission_by_id(sub_id)
        if not sub or sub["status"] != "pending":
            await call.answer("Already processed.", show_alert=True)
            return

        update_submission_status(sub_id, "approved")
        add_balance(sub["user_id"], TASK_PRICE)

        # Save to persistent xlsx file
        append_to_xlsx(sub["uid"], sub["cookies"])

        # Check referral commission
        user = get_user(sub["user_id"])
        if user and user.get("referred_by"):
            commission = round(TASK_PRICE * REFERRAL_COMMISSION, 6)
            add_balance(user["referred_by"], commission)
            log_referral_earning(user["referred_by"], sub["user_id"], commission)

        # Notify the worker
        try:
            worker_lang = get_user_lang(sub["user_id"])
            await bot.send_message(
                sub["user_id"],
                TRANSLATIONS[worker_lang]["approved_notify"].format(amount=TASK_PRICE),
                parse_mode=ParseMode.HTML,
            )
        except Exception:
            pass

        await call.answer("✅ Approved!", show_alert=True)
        # Refresh — show next pending or updated list
        await send_review_card(call.message.chat.id, 0, call.message.message_id)

    elif action == "reject":
        sub_id = int(parts[2])
        sub = get_submission_by_id(sub_id)
        if not sub or sub["status"] != "pending":
            await call.answer("Already processed.", show_alert=True)
            return

        update_submission_status(sub_id, "rejected")

        # Notify the worker
        try:
            worker_lang = get_user_lang(sub["user_id"])
            await bot.send_message(
                sub["user_id"],
                TRANSLATIONS[worker_lang]["rejected_notify"],
                parse_mode=ParseMode.HTML,
            )
        except Exception:
            pass

        await call.answer("❌ Rejected.", show_alert=True)
        await send_review_card(call.message.chat.id, 0, call.message.message_id)


# ─────────────────────────────────────────────
# ADMIN: /xl — Export XLSX (UID + Cookies)
# ─────────────────────────────────────────────
@router.message(Command("xl"))
async def cmd_xl(message: Message):
    """Send the persistent xlsx file that accumulates approved submissions."""
    if not is_admin(message.from_user.id):
        return

    file_bytes = get_xlsx_bytes()
    row_count = get_xlsx_row_count()

    await message.answer_document(
        document=BufferedInputFile(file_bytes, filename="approved_submissions.xlsx"),
        caption=f"📊 <b>Approved Submissions</b>\n\n✅ Total records: <b>{row_count}</b>",
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# ADMIN: /reset — Delete all approved submissions & restart collection
# ─────────────────────────────────────────────
@router.message(Command("reset"))
async def cmd_reset(message: Message):
    """
    Admin command: clear the xlsx file (reset collected data),
    then send a fresh empty xlsx to all admins.
    Database submissions are NOT deleted — only the xlsx is wiped.
    """
    if not is_admin(message.from_user.id):
        return

    # How many rows were in xlsx before reset
    old_count = get_xlsx_row_count()

    # Wipe the xlsx file (keeps header only)
    reset_xlsx()

    await message.answer(
        f"🔄 <b>Reset Complete!</b>\n\n"
        f"🗑 <b>{old_count}</b> record(s) xlsx থেকে মুছে গেছে।\n"
        f"📊 নতুন collection শুরু হয়েছে।",
        parse_mode=ParseMode.HTML,
    )

    # Send fresh empty xlsx to all admins
    file_bytes = get_xlsx_bytes()
    for admin_id in {MAIN_ADMIN, SECOND_ADMIN_ID}:
        if admin_id:
            try:
                await bot.send_document(
                    chat_id=admin_id,
                    document=BufferedInputFile(file_bytes, filename="approved_submissions_new.xlsx"),
                    caption=(
                        f"📋 <b>Fresh Collection Started</b>\n\n"
                        f"🗑 আগের <b>{old_count}</b>টা record মুছে গেছে।\n"
                        f"✅ এখন থেকে নতুন approved submissions এখানে জমা হবে।"
                    ),
                    parse_mode=ParseMode.HTML,
                )
            except Exception as e:
                logger.warning(f"Could not notify admin {admin_id} about reset: {e}")


# ─────────────────────────────────────────────
# ADMIN: /stats — Bot statistics
# ─────────────────────────────────────────────
@router.message(Command("stats"))
async def cmd_stats(message: Message):
    """Show bot-wide statistics."""
    if not is_admin(message.from_user.id):
        return

    s = get_global_stats()
    text = (
        "📊 <b>Bot Statistics</b>\n\n"
        f"👥 <b>Total Users:</b> {s['total_users']}\n"
        f"📤 <b>Submitted:</b> {s['submitted']}\n"
        f"✅ <b>Approved:</b> {s['approved']}\n"
        f"❌ <b>Rejected:</b> {s['rejected']}\n"
        f"⏳ <b>Pending:</b> {s['pending']}\n"
        f"💰 <b>Total Paid:</b> ${s['total_paid']:.4f}\n"
        f"💵 <b>Total Withdrawals:</b> ${s['total_withdrawals']:.4f}"
    )
    await message.answer(text, parse_mode=ParseMode.HTML)


# ─────────────────────────────────────────────
# FALLBACK HANDLER
# ─────────────────────────────────────────────
@router.message()
async def fallback_handler(message: Message, state: FSMContext):
    """
    Catch-all handler for unrecognized messages.
    If the user is mid-flow, we let FSM handle it above.
    Otherwise, gently guide them home.
    """
    current_state = await state.get_state()
    if current_state is not None:
        # Mid-flow — don't interfere
        return
    uid = message.from_user.id
    ensure_user(
        uid,
        message.from_user.username or "",
        message.from_user.full_name or "",
    )
    await message.answer(
        t(uid, "welcome"),
        reply_markup=home_keyboard(uid),
        parse_mode=ParseMode.HTML,
    )


# ─────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────
async def main():
    """Initialize bot, database, and start polling."""
    global bot

    # Initialize the database and xlsx file
    init_db()
    ensure_xlsx()

    # Create bot instance with HTML parse mode default
    bot = Bot(
        token=BOT_TOKEN,
        default=DefaultBotProperties(parse_mode=ParseMode.HTML),
    )

    dp = Dispatcher(storage=MemoryStorage())
    dp.include_router(router)

    logger.info("🚀 axFounder Bot is starting...")
    await bot.delete_webhook(drop_pending_updates=True)
    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())
